import type { Opportunity } from './types'

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 1,
    title: 'MIT Research Internship',
    description:
      'A competitive summer research internship at MIT Labs. Work alongside world-class researchers on cutting-edge projects in artificial intelligence, robotics, and computational biology. Publish your findings in peer-reviewed journals.',
    tags: ['Research', 'AI', 'STEM'],
    organization: 'MIT Labs',
    location: 'Cambridge, USA',
    coordinates: { lat: 42.3601, lng: -71.0942 },
    startDate: '2026-07-07T09:00:00.000Z',
    applyUrl: 'https://mit.edu/research-internship',
    matchPercentage: 92,
    imageIcon: '\uD83D\uDD2C',
  },
  {
    id: 2,
    title: 'Stanford Engineering Workshop',
    description:
      'An intensive two-week engineering workshop at Stanford University. Participants engage in hands-on prototyping, hardware design, and software development. Network with industry leaders and Silicon Valley innovators.',
    tags: ['Engineering', 'Workshop', 'Hardware'],
    organization: 'Stanford University',
    location: 'Stanford, USA',
    coordinates: { lat: 37.4275, lng: -122.1697 },
    startDate: '2026-07-23T10:00:00.000Z',
    applyUrl: 'https://stanford.edu/engineering-workshop',
    matchPercentage: 78,
    imageIcon: '\u2699\uFE0F',
  },
  {
    id: 3,
    title: 'Google AI Summit 2026',
    description:
      'The premier artificial intelligence summit hosted by Google. Features keynote speeches from DeepMind researchers, hands-on TensorFlow workshops, and breakout sessions on LLMs, computer vision, and responsible AI.',
    tags: ['AI', 'Summit', 'Tech'],
    organization: 'Google',
    location: 'Mountain View, USA',
    coordinates: { lat: 37.3861, lng: -122.0839 },
    startDate: '2026-06-30T08:00:00.000Z',
    applyUrl: 'https://ai.google/summit-2026',
    matchPercentage: 85,
    imageIcon: '\uD83E\uDD16',
  },
  {
    id: 4,
    title: 'WHO Medical Innovation Program',
    description:
      'A global health innovation program organized by the World Health Organization. Design and implement digital health solutions for underserved communities. Collaborate with international health experts and policymakers.',
    tags: ['Healthcare', 'Innovation', 'Global'],
    organization: 'World Health Organization',
    location: 'Geneva, Switzerland',
    coordinates: { lat: 46.2321, lng: 6.1332 },
    startDate: '2026-08-22T09:00:00.000Z',
    applyUrl: 'https://who.int/innovation-program',
    matchPercentage: 71,
    imageIcon: '\uD83C\uDF0D',
  },
  {
    id: 5,
    title: 'NASA Space Technology Fellowship',
    description:
      'A prestigious fellowship program at NASA Johnson Space Center. Selected fellows work on real space missions, from satellite design to Mars rover navigation. Includes a stipend and potential for full-time employment.',
    tags: ['Space', 'Fellowship', 'STEM'],
    organization: 'NASA',
    location: 'Houston, USA',
    coordinates: { lat: 29.5597, lng: -95.0915 },
    startDate: '2026-09-21T08:00:00.000Z',
    applyUrl: 'https://nasa.gov/fellowship',
    matchPercentage: 63,
    imageIcon: '\uD83D\uDE80',
  },
  {
    id: 6,
    title: 'UNEP Environmental Leadership Summit',
    description:
      'A gathering of young environmental leaders at the United Nations Environment Programme headquarters. Develop actionable strategies for climate resilience, sustainable agriculture, and ocean conservation.',
    tags: ['Environment', 'Leadership', 'Sustainability'],
    organization: 'UN Environment Programme',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    startDate: '2026-08-07T09:00:00.000Z',
    applyUrl: 'https://unep.org/youth-summit',
    matchPercentage: 88,
    imageIcon: '\uD83C\uDF31',
  },
  {
    id: 7,
    title: 'Microsoft Coding Bootcamp',
    description:
      'An immersive full-stack coding bootcamp at Microsoft headquarters. Learn React, TypeScript, cloud computing with Azure, and agile development practices. Build real products and present to Microsoft engineering leads.',
    tags: ['Coding', 'Bootcamp', 'Cloud'],
    organization: 'Microsoft',
    location: 'Redmond, USA',
    coordinates: { lat: 47.674, lng: -122.1215 },
    startDate: '2026-06-26T09:00:00.000Z',
    applyUrl: 'https://microsoft.com/bootcamp',
    matchPercentage: 95,
    imageIcon: '\uD83D\uDCBB',
  },
]
